allowBuilds:
  lefthook: true
  nx: false
  unrs-resolver: true
catalog:
  "@actions/core": ^2.0.3
  "@actions/exec": ^2.0.0
  "@actions/github": ^6.0.1
  "@octokit/core": ^7.0.8
  "@storm-software/config": ^1.138.82
  "@storm-software/config-tools": ^1.190.146
  "@storm-software/cspell": ^0.46.213
  "@storm-software/eslint": ^0.170.181
  "@storm-software/eslint-plugin-tsdoc": ^0.0.109
  "@storm-software/git-tools": ^2.132.3
  "@storm-software/linting-tools": ^1.134.76
  "@storm-software/markdownlint": ^0.30.301
  "@storm-software/pnpm-tools": ^0.7.160
  "@storm-software/prettier": ^0.59.199
  "@storm-software/tsconfig": ^0.48.212
  "@types/node": ^25.9.9
  handlebars: ^4.7.9
  tsdown: ^0.23.0
  undici: ^6.27.0
  unrs-resolver: ^1.12.2
  zx: ^8.8.5
  prettier: ^3.9.9
  rimraf: ^6.1.3
  lefthook: ^1.13.6
  eslint: ^10.12.0
  copyfiles: ^2.4.1
shamefullyHoist: true
engineStrict: true
fetchTimeout: 240000
dedupeDirectDeps: true
dedupePeerDependents: true
cleanupUnusedCatalogs: true
minimumReleaseAge: 800
minimumReleaseAgeExclude:
  - "@storm-software/*"
  - conventional-changelog-storm-software
